### ISSUE TITLE
IVRController needs a mechanism to retry

### ISSUE THREAD

**Issue by bklang** [adhearsion/adhearsion-ivr#11]
Grammars only go so far.  Grammars may match something like "enter 5 digits", but then application code has to determine whether those 5 digits are a real account ID, or whether the current caller has access to that account (or whatever else those digits may signify).  Ideally, you want the same retry logic to apply when someone gets a bad match vs. bad input.  I'm not sure whether we want to throw something in the `on_complete` callback, or add a new `validate_input` callback.

@benlangfeld @victorluft thoughts?

**Comment by victorluft** [comment]
`validate_input` seems logical me. state machine would be `prompting` -> `validation` -> `input_error` or `completion`

**Comment by victorluft** [comment]
Any thoughts on handling the situation where we'd want different retry prompts for bad match vs. bad input? I suspect this may be not uncommon.

**Comment by bklang** [comment]
Can you give an example of what you mean by "bad match" vs. "bad input"?

**Comment by victorluft** [comment]
Bad match as in ASR failed, bad input as in validation failed. For a zip code example, say, may want different prompts for "I didn't catch that" vs. "That's not a zip code in our database."

**Comment by bklang** [comment]
Ah, makes sense.  It did occur to me the other day that we should do something about those prompts.  Right now it's a static list.  I'm open to defining a new API for figuring out prompts.

**Comment by benlangfeld** [comment]
I think #12 is a good solution to this, and I don't have anything to add to it right now.
